version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: myfood
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myfood

volumes:
  .postgres-data:
